imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@disanBundle/Resources/config/services.yml" }
    - { resource: "@jpmBundle/Resources/config/services.yml" }
    - { resource: "@calificacionBundle/Resources/config/services.yml" }
    - { resource: "@comandanteBundle/Resources/config/services.yml" }
    - { resource: "@matricesBundle/Resources/config/services.yml" }
    - { resource: "@adminBundle/Resources/config/services.yml" }
    - { resource: "@loginBundle/Resources/config/services.yml" }
    

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: dbal
        connections:
            dbal:
                driver:   oci8
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                service:  "%database_service%"  
                user:     "%database_user%"
                password: "%database_password%"
                charset:    UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        entity_managers:
            dbal1:
                connection:   dbal
                mappings:
                    calificacionBundle: ~
                    disanBundle: ~
                    jpmBundle: ~
                    comandanteBundle: ~
                    loginBundle: ~
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
# knp snappy generador de paginas PDF 
knp_snappy:
    pdf:
        enabled:    true
        binary:    "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    
            no-outline: true
            page-size: LETTER
            # Recommended to set UTF-8 as default encoding :)
            encoding: UTF-8
    image:
        enabled:    true
        binary:      "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []

# knp pagination bundle
knp_paginator:
    page_range: 4
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    # template:
    #     pagination: calificacionBundle:default:paginador.html.twig
# nelmio_cors:
#     defaults:
#         allow_credentials: true
#         allow_origin: []
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         max_age: 0
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#     paths:
#         '^/login/ldap':
#             allow_origin: ['http://localhost:4200']
#             allow_headers: ['origin', 'content-type', 'authorization']
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             max_age: 3600
#         '^/login/ldap':
#             origin_regex: true
#             allow_origin: ['^http://localhost:[0-9]+']
#             allow_headers: ['*']
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             max_age: 3600
#             hosts: []


